apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: infra
spec:
  entryPoints:
    - docker
  routes:
  - match: Host(`127.0.0.1`)
    kind: Rule
    services:
    - name: harbor-portal
      port: 80
  - match: Host(`127.0.0.1`) && PathPrefix(`/api/`, `/service/`, `/v2/`, `/chartrepo/`, `/c/`)
    kind: Rule
    services:
    - name: harbor-core
      port: 80
  tls:
    secretName: localhost-tls-secret