apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-extra
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/alexchiri/argo-play.git
    path: extra/argocd-extra
    targetRevision: alpha
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true