apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: infra
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 7.3.3
    helm:
      releaseName: grafana
      valuesObject:
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
            - name: 'grafana-dashboards-kubernetes'
              orgId: 1
              folder: 'Kubernetes'
              type: file
              disableDeletion: true
              editable: true
              options:
                path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
        dashboards:
          grafana-dashboards-kubernetes:
            k8s-views-global:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
              token: ''
            k8s-views-nodes:
              url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
              token: ''
          default:
            logs:
              json: |
                {
                  "__inputs": [
                    {
                      "name": "DS_LOKI",
                      "label": "Loki",
                      "description": "",
                      "type": "datasource",
                      "pluginId": "loki",
                      "pluginName": "Loki"
                    },
                    {
                      "name": "DS_PROMETHEUS",
                      "label": "Prometheus",
                      "description": "",
                      "type": "datasource",
                      "pluginId": "prometheus",
                      "pluginName": "Prometheus"
                    }
                  ],
                  "__elements": {},
                  "__requires": [
                    {
                      "type": "grafana",
                      "id": "grafana",
                      "name": "Grafana",
                      "version": "10.3.3"
                    },
                    {
                      "type": "panel",
                      "id": "logs",
                      "name": "Logs",
                      "version": ""
                    },
                    {
                      "type": "datasource",
                      "id": "loki",
                      "name": "Loki",
                      "version": "1.0.0"
                    },
                    {
                      "type": "datasource",
                      "id": "prometheus",
                      "name": "Prometheus",
                      "version": "1.0.0"
                    }
                  ],
                  "annotations": {
                    "list": [
                      {
                        "builtIn": 1,
                        "datasource": {
                          "type": "grafana",
                          "uid": "-- Grafana --"
                        },
                        "enable": true,
                        "hide": true,
                        "iconColor": "rgba(0, 211, 255, 1)",
                        "name": "Annotations & Alerts",
                        "type": "dashboard"
                      }
                    ]
                  },
                  "editable": true,
                  "fiscalYearStartMonth": 0,
                  "graphTooltip": 0,
                  "id": null,
                  "links": [],
                  "liveNow": false,
                  "panels": [
                    {
                      "datasource": {
                        "type": "loki",
                        "uid": "loki"
                      },
                      "gridPos": {
                        "h": 22,
                        "w": 24,
                        "x": 0,
                        "y": 0
                      },
                      "id": 1,
                      "options": {
                        "dedupStrategy": "none",
                        "enableLogDetails": true,
                        "prettifyLogMessage": true,
                        "showCommonLabels": false,
                        "showLabels": false,
                        "showTime": true,
                        "sortOrder": "Descending",
                        "wrapLogMessage": false
                      },
                      "targets": [
                        {
                          "datasource": {
                            "type": "loki",
                            "uid": "loki"
                          },
                          "editorMode": "code",
                          "expr": "{pod=\"$pod\"}",
                          "queryType": "range",
                          "refId": "A"
                        }
                      ],
                      "title": "Pod Logs",
                      "type": "logs"
                    }
                  ],
                  "refresh": "",
                  "schemaVersion": 39,
                  "tags": [],
                  "templating": {
                    "list": [
                      {
                        "current": {},
                        "datasource": {
                          "type": "prometheus",
                          "uid": "prometheus"
                        },
                        "definition": "label_values(namespace)",
                        "hide": 0,
                        "includeAll": false,
                        "multi": false,
                        "name": "namespace",
                        "options": [],
                        "query": {
                          "qryType": 1,
                          "query": "label_values(namespace)",
                          "refId": "PrometheusVariableQueryEditor-VariableQuery"
                        },
                        "refresh": 1,
                        "regex": "",
                        "skipUrlSync": false,
                        "sort": 0,
                        "type": "query"
                      },
                      {
                        "current": {},
                        "datasource": {
                          "type": "prometheus",
                          "uid": "prometheus"
                        },
                        "definition": "label_values({namespace=\"$namespace\"},pod)",
                        "hide": 0,
                        "includeAll": false,
                        "multi": false,
                        "name": "pod",
                        "options": [],
                        "query": {
                          "qryType": 1,
                          "query": "label_values({namespace=\"$namespace\"},pod)",
                          "refId": "PrometheusVariableQueryEditor-VariableQuery"
                        },
                        "refresh": 1,
                        "regex": "",
                        "skipUrlSync": false,
                        "sort": 0,
                        "type": "query"
                      }
                    ]
                  },
                  "time": {
                    "from": "2024-03-14T12:24:56.148Z",
                    "to": "2024-03-15T00:24:56.148Z"
                  },
                  "timepicker": {},
                  "timezone": "",
                  "title": "Logs",
                  "uid": "e0f18498-caf6-44b0-98f2-1401479a1b4f",
                  "version": 1,
                  "weekStart": ""
                }
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server
                access: proxy
                isDefault: true
                uid: prometheus
              - name: Loki
                type: loki
                access: proxy
                uid: loki
                url: http://loki-gateway
                basicAuth: false
                jsonData:
                  timeout: 60
                  maxLines: 1000
        grafana.ini:
          log:
            mode: console
            level: debug
          server:
            root_url: "https://127.0.0.1/grafana"
            serve_from_sub_path: true
          auth:
            disable_login_form: true
          auth.anonymous:
            enabled: true
            org_role: Admin
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true