apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: infra
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.14.0
    helm:
      releaseName: harbor
      valuesObject:
        expose:
          tls:
            enabled: false
          ingress:
            hosts:
              core: 127.0.0.1
            annotations:
              ingress.kubernetes.io/ssl-redirect: null
              nginx.ingress.kubernetes.io/ssl-redirect: null
        externalURL: https://127.0.0.1/harbor
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true