apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: infra
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.14.0
    helm:
      releaseName: harbor
      valuesObject:
        expose:
          type: clusterIP
          tls:
            enabled: false
        externalURL: https://127.0.0.1:8888
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true