apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: infra
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.14.0
    helm:
      releaseName: harbor
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra