apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: infra
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.43.6
    helm:
      releaseName: loki
      valuesObject:
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
        write:
          replicas: 1
        read:
          replicas: 1
        backend:
          replicas: 1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true