apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: infra
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.17.0
    helm:
      releaseName: prometheus
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true